### ISSUE TITLE
Is it possible to build a testbed using Colosseum-Scope, Colosseum-Scope-E2, and Colosseum-Near-RT-RIC without using the Colosseum Emulator, but instead using an SDR?

### ISSUE THREAD

**Issue by JJinsup** [wineslab/colosseum-scope#11]
I am currently using a dockerized Open5GS connected to an srsRAN_4G eNB, with a B210 SDR to connect a COTS UE to the eNB.
![image](https://github.com/user-attachments/assets/07d23cfb-9acc-4432-900c-2ef6ecdaa871)
![image](https://github.com/user-attachments/assets/916bd97b-d924-44d5-a748-3e87ccf8f24b)

I tried modifying the scope_start.py and the config files within the srslte_config folder and ran them, but it did not work.

jin@jin-400TFA-400SFA:~/colosseum-scope/radio_api$ python3 scope_start.py 
/home/jin/colosseum-scope/radio_api/scope_start.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.util
2024-11-15 17:47:52,424 INFO     Parsed configuration:
2024-11-15 17:47:52,424 INFO     capture-pkts                    False
2024-11-15 17:47:52,424 INFO     colosseumcli                    False
2024-11-15 17:47:52,424 INFO     generic-testbed                 False
2024-11-15 17:47:52,425 INFO     node-is-bs                      False
2024-11-15 17:47:52,425 INFO     ue-id                           1
2024-11-15 17:47:52,425 INFO     iperf                           False
2024-11-15 17:47:52,425 INFO     users-bs                        3
2024-11-15 17:47:52,425 INFO     write-config-parameters         False
2024-11-15 17:47:52,425 INFO     network-slicing                 False
2024-11-15 17:47:52,425 INFO     global-scheduling-policy        0
2024-11-15 17:47:52,425 INFO     slice-scheduling-policy         None
2024-11-15 17:47:52,425 INFO     tenant-number                   2
2024-11-15 17:47:52,425 INFO     slice-allocation                None
2024-11-15 17:47:52,425 INFO     custom-ue-slice                 False
2024-11-15 17:47:52,425 INFO     dl-freq                         1020000000
2024-11-15 17:47:52,425 INFO     ul-freq                         980000000
2024-11-15 17:47:52,425 INFO     dl-prb                          50
2024-11-15 17:47:52,425 INFO     force-dl-modulation             False
2024-11-15 17:47:52,425 INFO     force-ul-modulation             False
2024-11-15 17:47:52,425 INFO     slice-users                     None
2024-11-15 17:47:52,425 INFO     bs-config                       None
2024-11-15 17:47:52,425 INFO     ue-config                       None
2024-11-15 17:47:52,425 INFO     Getting configuration parameters...
2024-11-15 17:47:52,425 INFO     colosseum-testbed True
2024-11-15 17:47:52,425 INFO     global-scheduling-policy 0
2024-11-15 17:47:52,425 INFO     force-dl-modulation False
2024-11-15 17:47:52,425 INFO     force-ul-modulation False
2024-11-15 17:47:52,425 INFO     network-slicing False
2024-11-15 17:47:52,425 INFO     
2024-11-15 17:47:52,425 INFO     Did you remember to pass a configuration file? :-)

Traceback (most recent call last):
  File "/home/jin/colosseum-scope/radio_api/scope_start.py", line 814, in <module>
    config_params = get_config_params(config)
  File "/home/jin/colosseum-scope/radio_api/scope_start.py", line 307, in get_config_params
    passed_value = ast.literal_eval(config[param_key])
  File "/usr/lib/python3.10/ast.py", line 110, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.10/ast.py", line 109, in _convert
    return _convert_signed_num(node)
  File "/usr/lib/python3.10/ast.py", line 83, in _convert_signed_num
    return _convert_num(node)
  File "/usr/lib/python3.10/ast.py", line 74, in _convert_num
    _raise_malformed_node(node)
  File "/usr/lib/python3.10/ast.py", line 71, in _raise_malformed_node
    raise ValueError(msg + f': {node!r}')
ValueError: malformed node or string: None

  "generic-testbed": "True", this option is in radio_interactive.conf if we using the radio_generic.conf
  it works?
  
  we follow this page
  https://openrangym.com/tutorials/scope-coloran-o-ran

**Comment by leonardobonati** [comment]
It should work, please also note that Colosseum uses SDRs as well. The error above looks like a Python dependency issue.
